development:
  adapter: postgresql
  encoding: unicode
  database: brain_pick-dev
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  database: brain_pick-test
  pool: 5
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: brain_pick-prod
  pool: 5
  host: localhost
  username:
  password:
