# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96a6e73184a9b8ed27f2a81fdad42995cae748c425118b5c29eed021d0ad4f938ad7d545cb7ead51c32b0fa7933515aca06c48db6137dd283142cee4a8ec3cb6

test:
  secret_key_base: af1eb2ea45b96756316964562e1cf121fed596c385039e4977de1c6d720f944fe0b07d1f4ce5fe0f2da71957dcf62fd1450362d72432781c10c385b53ac90545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
